import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Footer } from '../components/Footer'
import { Heading } from '../components/Heading'
import { Navbar } from '../components/Navbar'
import img from '../pages/photo/AboutUs.png'
import about from '../styles/AboutUs.module.css'
import logo1 from '../pages/photo/aboutus1.png'
import logo2 from '../pages/photo/aboutus2.png'
import logo3 from '../pages/photo/aboutus3.png'
import logo4 from '../pages/photo/aboutus4.png'
import { Container } from '@mui/system'




const AboutUs: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Heading />
			<Navbar />
			<div className={about.pageBox}>
			<Container>
				<div>
					
					<h1 className={about.Title}>About Us</h1>

					<span className={about.page}>Home. Pages.</span>
					<span className={about.nowPage}>
					About Us
					</span>
					
				</div>
				
				
				</Container>
			</div>

			<div className={about.mainTopic}>
				<Image src={img} />
				<div className={about.content}>
					<h2 className={about.Topic}>
						Know About Our Ecomerce Business, History
					</h2>
					<div className={about.topicContent}>
						Lorem ipsum dolor sit amet, consectetur adipiscing elit.
						Mattis neque ultrices mattis aliquam, malesuada diam
						est. Malesuada sem tristique amet erat vitae eget dolor
						lobortis. Accumsan faucibus vitae lobortis quis bibendum
						quam.
					</div>
					<Link href='/ContactUs'>
						<a className={about.contactButton}>Contact us</a>
					</Link>
				</div>
			</div>

			<div className={about.featuresTopic}>
				<h3 className={about.featuresTitle}>Our Features</h3>

				<div className={about.cardBox}>
					<div className={about.card}>
						<Image src={logo1} />
						<p className={about.cardTopic}>Free Delivery</p>
						<p className={about.cardContact}>
							Lorem ipsum dolor sit amet, consectetur adipiscing
							elit. Massa purus gravida.
						</p>
					</div>
					<div className={about.card}>
						<Image src={logo2} />
						<p className={about.cardTopic}>100% Cash Back</p>
						<p className={about.cardContact}>
							Lorem ipsum dolor sit amet, consectetur adipiscing
							elit. Massa purus gravida.
						</p>
					</div>
					<div className={about.card}>
						<Image src={logo3} />
						<p className={about.cardTopic}>Quality Product</p>
						<p className={about.cardContact}>
							Lorem ipsum dolor sit amet, consectetur adipiscing
							elit. Massa purus gravida.
						</p>
					</div>
					<div className={about.card}>
						<Image src={logo4} />
						<p className={about.cardTopic}>24/7 Support</p>
						<p className={about.cardContact}>
							Lorem ipsum dolor sit amet, consectetur adipiscing
							elit. Massa purus gravida.
						</p>
					</div>
				</div>


			</div>

			<Footer />
		</div>
	)
}

export default AboutUs
