import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Footer } from '../components/Footer'
import { Heading } from '../components/Heading'
import { Navbar } from '../components/Navbar'
import orderComplet from '../styles/OrderCompleted.module.css'
import completed from '../pages/photo/completed.png'
import Link from 'next/link'
import { Container } from '@mui/material'

const orderCompleted: NextPage = () => {
	return (
		<div>
			<Heading />
			<Navbar />

			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div className={orderComplet.pageBox}>
			<Container>
				<div>
					
					<h1 className={orderComplet.Title}>Order Completed</h1>

					<span className={orderComplet.page}>Home. Pages.</span>
					<span className={orderComplet.nowPage}>
					Order Completed
					</span>
					
				</div>
				
				
				</Container>
			</div>
		

			<div className={orderComplet.box}>
				<div className={orderComplet.boxBorder}>
					<Image src={completed} />
					<h1>Your Order Is Completed !</h1>
					<p className={orderComplet.completedWord}>
						Thank you for your order! Your order is being processed
						and will be completed within 3-6 hours. <br />
						<br />
						You will receive an email confirmation when your order
						is completed.
					</p>
					<Link href='/productPage'>
						<a className={orderComplet.shoppingPageButton}>
							Continue Shopping
						</a>
					</Link>
				</div>
			</div>

			<Footer />
		</div>
	)
}

export default orderCompleted
